### ISSUE TITLE
vm create gives set faults

### ISSUE THREAD

**Issue by sebgoa** [exoscale/egoscale#310]
I created my first VM using `exo`, the VM does start properly but the CLI gives a seg fault:

```
$ exo vm create foobar -k egoscale -o tiny
Deploying "foobar" 100 % [======================================] done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x140c11a]

goroutine 1 [running]:
github.com/exoscale/egoscale/cmd/exo/cmd.glob..func52(0x17f2080, 0xc420258050, 0x1, 0x5, 0x0, 0x0)
	/go/src/github.com/exoscale/egoscale/cmd/exo/cmd/vm_create.go:155 +0x8fa
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).execute(0x17f2080, 0xc420258000, 0x5, 0x5, 0x17f2080, 0xc420258000)
	/go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x17f01a0, 0xc420169f00, 0x20, 0x13f6257)
	/go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).Execute(0x17f01a0, 0x154c858, 0xc420121800)
	/go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/exoscale/egoscale/cmd/exo/cmd.Execute()
	/go/src/github.com/exoscale/egoscale/cmd/exo/cmd/root.go:97 +0x16d
main.main()
	/go/src/github.com/exoscale/egoscale/cmd/exo/main.go:11 +0x2f
```

**Comment by sebgoa** [comment]
delete has the same error, the progress bar has an issue I believe.

**Comment by pierre-emmanuelJ** [comment]
I fixed it on master but I have to push a new release to have change

**Comment by pierre-emmanuelJ** [comment]
https://github.com/exoscale/egoscale/releases/tag/v0.11.3

**Comment by greut** [comment]
@sebgoa as pointed out by @pierre-emmanuelJ the v0.11.3 should contain the fix. Thank for your report and keep us posted if you encounter anything unexpected either good or bad.

**Comment by TimoKramer** [comment]
problem seems to still exist
```
$ exo version 
exo version 0.11.3
$ exo vm create dispatcher -k timo -t 'Linux Debian 9 64-bit' -z de-fra-1 -d 10 -o micro                                                                                                               
Deploying "dispatcher" 100 % [======================================] done
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x809e2a]

goroutine 1 [running]:
github.com/exoscale/egoscale/cmd/exo/cmd.glob..func52(0xbee4a0, 0xc42024a0b0, 0x1, 0xb, 0x0, 0x0)
        /go/src/github.com/exoscale/egoscale/cmd/exo/cmd/vm_create.go:155 +0x8fa
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).execute(0xbee4a0, 0xc42024a000, 0xb, 0xb, 0xbee4a0, 0xc42024a000)
        /go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xbec5c0, 0xc42015ff00, 0x20, 0x7f3f17)
        /go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra.(*Command).Execute(0xbec5c0, 0x94a110, 0xc42006b860)
        /go/src/github.com/exoscale/egoscale/cmd/exo/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/exoscale/egoscale/cmd/exo/cmd.Execute()
        /go/src/github.com/exoscale/egoscale/cmd/exo/cmd/root.go:97 +0x16d
main.main()
        /go/src/github.com/exoscale/egoscale/cmd/exo/main.go:11 +0x2f
```

**Comment by pierre-emmanuelJ** [comment]
thanks @TimoKramer to report, I will fix it and release ASAP.
